### ISSUE TITLE
IP地址反馈

### ISSUE THREAD

**Issue by luwah** [DH-Teams/DH-Geo_AS_IP_CN#1]
拟访问域名：license.wsb003.cn
DNS返回IP：121.46.19.183
不在列表121.46.0.0/20, 121.46.20.0/22范围内
但该IP属于广东，并且该域名无法通过代理访问

起因：访问该域名无法打开网页，关闭代理后可以打开，查询后发现域名没有通过geoip,cn,direct直连，而是通过final,proxy连接。

**Comment by DH-Teams** [comment]
该地址广播在[AS135391] 和CM，CT进行CN范围内广播，所以在国内，国外都可正常连接。

但是我们不会对这种地址进行CN收录，因为这个破坏了BGP 路由公告的合法性。
